project:
  type: website
  output-dir: docs


website:
  title: "Hello world"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - text: "db"
        menu: 
          - qmd/ncbi.qmd
          - qmd/ensembl.qmd
          - qmd/tcga.qmd
      - qmd/data_format.qmd

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
        - qmd/tcga.qmd
        - qmd/ncbi.qmd
      - section: "Basics1"
        contents:
        - qmd/tcga.qmd
        - qmd/ncbi.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

