project:
  type: website
  output-dir: docs

website:
  title: "Bioinfor"
  navbar:
    left:
      - text: Home
        href: index.qmd
        
      - text: "Bioinformatics"
        href: qmd/01_bioinformatics/01_index.qmd

      - text: "Pipeline"
        href: qmd/02_pipeline/01_index.qmd
          
      - text: "ML"
        href: qmd/03_ml/01_index.qmd
      
      - text: "Tools"
        href: qmd/04_tools/01_index.qmd

    right:
      - icon: twitter
        href: https://twitter.com/SQiangqiang
      - icon: github
        href: https://github.com/Jinjin89
        aria-label: github
      - icon: linkedin
        href: https://linkedin.com/in/keke-sun-6a9371267
        
  sidebar: 
    - id: Bioinformatics
      title: "Bioinformatics"
      style: floating
      collapse-level: 2
      alignment: left
      contents: 
        - text: "Bioinformatics"
          href: qmd/01_bioinformatics/01_index.qmd
        - section: "database"
          contents: 
          - qmd/01_bioinformatics/11_ncbi.qmd
          - qmd/01_bioinformatics/12_ensembl.qmd
          - qmd/01_bioinformatics/13_genome.qmd
          - qmd/01_bioinformatics/14_tcga.qmd
        - section: "sc"
          contents: 
            - qmd/01_bioinformatics/21_sc.qmd
        - section: "format"
          contents:
          - qmd/01_bioinformatics/31_data_format.qmd

        - text: Omics
          href: qmd/01_bioinformatics/41_omics.qmd
  
    - id: Pipeline
      title: Pipeline
      style: floating
      collapse-level: 2
      alignment: left
      contents: 
        - text: "Pipeline"
          href: qmd/02_pipeline/01_index.qmd
        - href: qmd/02_pipeline/11_dna.qmd
        - href: qmd/02_pipeline/21_rna.qmd
        - href: qmd/02_pipeline/31_metagenomics.qmd
        
    - id: ML
      title: "Machine learning"
      style: floating
      collapse-level: 2
      alignment: left
      contents: 
        - text: "ML in bio"
          href: qmd/03_ml/01_index.qmd
          
    - id: Tools
      style: floating
      collapse-level: 2
      alignment: left
      contents: 
        - text: "Tools"
          href: qmd/04_tools/01_index.qmd
        - href: qmd/04_tools/11_git.qmd
        - href: qmd/04_tools/12_restful.qmd
        - href: qmd/04_tools/13_r.qmd
        - href: qmd/04_tools/14_quarto_tools.qmd
        - href: qmd/04_tools/15_docker.qmd
        - href: qmd/04_tools/16_linux.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-line-numbers: true
    code-copy: true

editor: source

