project:
  type: website
  output-dir: docs

website:
  title: "Bioinfor"
  navbar:
    left:
      - text: Home
        href: index.qmd
        
      - text: "Bioinformatics"
        href: qmd/bioinformatics/index.qmd
        
      - text: "ML"
        href: qmd/ml/index.qmd
      
      - text: "Pipeline"
        href: qmd/pipeline/index.qmd
        
      - text: "Tools"
        href: qmd/tools/index.qmd
        

        
    right:
      - icon: twitter
        href: https://twitter.com/SQiangqiang
      - icon: github
        href: https://github.com/Jinjin89
        aria-label: github
      - icon: linkedin
        href: https://linkedin.com/in/keke-sun-6a9371267
        
  sidebar: 
    - id: Bioinformatics
      title: "Bioinformatics"
      style: floating
      collapse-level: 2
      alignment: left
      contents: 
        - text: "Bioinformatics"
          href: qmd/bioinformatics/index.qmd
        - section: "database"
          contents: 
          - qmd/bioinformatics/ncbi.qmd
          - qmd/bioinformatics/ensembl.qmd
          - qmd/bioinformatics/genome.qmd
          - qmd/bioinformatics/tcga.qmd
        - section: "sc"
          contents: 
            - qmd/bioinformatics/sc.qmd
        - section: "format"
          contents:
          - qmd/bioinformatics/data_format.qmd

    - id: ML
      title: "Machine learning"
      style: floating
      collapse-level: 2
      alignment: left
      contents: 
        - text: "ML in bio"
          href: qmd/ml/index.qmd
        - href: qmd/ml/microscopist.qmd

    - id: Pipeline
      title: Pipeline
      style: floating
      collapse-level: 2
      alignment: left
      contents: 
        - text: "Pipeline"
          href: qmd/pipeline/index.qmd
        - href: qmd/pipeline/dna.qmd
        - href: qmd/pipeline/mrna.qmd
        - href: qmd/pipeline/metagenomics.qmd
        
    - id: Tools
      style: floating
      collapse-level: 2
      alignment: left
      contents: 
        - text: "Tools"
          href: qmd/tools/index.qmd
        - href: qmd/tools/git.qmd
        - href: qmd/tools/restful.qmd
        - href: qmd/tools/quarto_tools.qmd
        - href: qmd/tools/nginx.qmd
    
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-line-numbers: true
    code-copy: true

editor: source

